apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: techchallenge
type: Opaque
stringData:
  REDIS_URL: "redis://pos-togmaster-dev-redis.wlpcva.0001.use1.cache.amazonaws.com:6379"
  SERVICE_API_KEY: "tm_key_0ebe1ca4b3bb48ce77ed7e297d3cb3d9c14af959208424820b1f8308d780e87b"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/712819938659/pos-togmaster-dev-queue"
  AWS_REGION: "us-east-1"