apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: techchallenge
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  aws_sqs_url: "https://sqs.us-east-1.amazonaws.com/712819938659/pos-togmaster-dev-queue"
