apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: techchallenge
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: techchallenge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: analytics-service
  ports:
    - name: http
      port: 8005
      targetPort: http
      protocol: TCP