apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: techchallenge
type: Opaque
stringData:
  database_url: "postgres://postgres:TroqueEssaSenha123!@targeting-service.cpunrppperdh.us-east-1.rds.amazonaws.com:5432/targeting_db?sslmode=require"
