apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: techchallenge
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: techchallenge
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-service
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: techchallenge
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8001"
    spec:
      containers:
        - name: auth-service
          image: 712819938659.dkr.ecr.us-east-1.amazonaws.com/auth-service:c96e353
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8001
          env:
            - name: APP_NAME
              value: auth-service
            - name: PORT
              value: "8001"
            - name: OTEL_SERVICE_NAME
              value: auth-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=techchallenge,deployment.environment=dev"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DATABASE_URL
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: MASTER_KEY
            - name: BOOTSTRAP_API_KEYS
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: BOOTSTRAP_API_KEYS
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
