apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: techchallenge
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:TroqueEssaSenha123!@auth-service.cpunrppperdh.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=require"
  MASTER_KEY: "admin-secreto-123"