apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: techchallenge
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: techchallenge
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP