apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: techchallenge
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:TroqueEssaSenha123@flag-service.cpunrppperdh.us-east-1.rds.amazonaws.com:5432/flags_db?sslmode=require"
