apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: techchallenge
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:TroqueEssaSenha123!@flag-service.cpunrppperdh.us-east-1.rds.amazonaws.com:5432/flags_db?sslmode=require"
  POSTGRES_HOST: "flag-service.cpunrppperdh.us-east-1.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "TroqueEssaSenha123!"
  POSTGRES_DB: "flags_db"
