apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: techchallenge
  namespace: argocd
spec:
  description: Projeto GitOps do Tech Challenge
  sourceRepos:
    - 'https://github.com/Kaio4816/tech-challenge-fase-3.git'
  destinations:
    - namespace: techchallenge
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true